### ISSUE TITLE
Null array of points issue

### ISSUE THREAD

**Issue by touseefahmad** [aashari/android-opencv-camscanner#2]
i get this error when i try to call "nativeClass.getPoint(tempBitmap);"
// this is my error
Attempt to invoke virtual method 'org.opencv.core.Point[] org.opencv.core.MatOfPoint2f.toArray()' on a null object reference

**Comment by touseefahmad** [comment]
it always calls this block of code 
List<MatOfPoint2f> rectangles = getPoints(downscaled);
        if (rectangles.size() == 0) {
            return null;
        }

**Comment by pankaj046** [comment]
try this it sovle your issue. it show error when not detect rectangle in scan image
```
 if (isRectangle(approx, srcArea)) {
      rectangles.add(approx);
 }else{
       rectangles.add(approx);
 }
```
